### ISSUE TITLE
[Feature request / suggestion] Alignment generation method

### ISSUE THREAD

**Issue by xileF1337** [MullinsLab/Bio-Cigar#4]
Hi maintainers of Bio::Cigar,

This looks like a useful module for working with cigar strings in Perl, thanks for sharing it! One feature I am missing is the generation of an actual alignment from a cigar string and given target and query sequences. Have you considered adding this feature? Would you be interested in accepting a pull request if I implemented this?

More specifically, I imagine adding an object method `align($target, $query)` to the `Bio::Cigar` class that returns an array ref `[$aln_target, $aln_query]` where the returned sequences contain gap characters (`-`) to align them to the same length. What do you think?

**Comment by tsibley** [comment]
That sounds useful to me, and yes, I'd be interested in accepting a PR of an implementation. I no longer use Bio::Cigar regularly (the work I'm doing changed), but I'm happy to keep maintaining it and make sure it continues to work.

One small note is that for consistency with the rest of the API, I'd suggest using the term "reference" instead of "target".

**Comment by tsibley** [comment]
[Implemented on my fork](https://github.com/MullinsLab/Bio-Cigar/pull/5#issuecomment-1295639874) and released as 1.02.
